messages:
  # Placeholders:
  # {prefix}: reference to the prefix message set below
  # {rank}: reference to the rank of the player affected (or default rank if no rank has been assigned)


  prefix: "[&bCC&r]" # can be used in messages using the '{prefix}' placeholder

  # Join Leave messages (placeholder: {player} the target player)
  JoinMessage: "{prefix} {rank} {player} Has joined the game!"
  LeaveMessage: "{prefix} {rank} {player} Has left the game!"

  # Only sent to people with the 'crystalcore.vanish' permission
  SilentJoinMessage: "{prefix} {rank} {player} Has silently joined the game!" # sent when someone auto vanishes
  SilentLeaveMessage: "{prefix} {rank} {player} Has silently left the game!" # sent when someone leaves vanished
  SelfVanishMessage: "{prefix} You have vanished!"
  SelfUnvanishMessage: "{prefix} You have reappeared!"
  OtherVanishMessage: "{prefix} {rank} {player} Has vanished!"
  OtherUnvanishMessage: "{prefix} {rank} {player} Has reappeared!"

  # Rank messages (placeholder: {rank} new rank name)
  RankChangedMessage: "{prefix} &aYour rank has been updated to &r{rank}!"
  TempRankChangedMessage: "{prefix} &aYou have temporarily been given the &r{rank} &arank! your rank will revert back once you leave."
  RankDeletedMessage: "{prefix} &cThe rank you had has been deleted! you have been reverted to the default rank."

  # /nickname messages (placeholder: {nickname} new nickname)
  NicknameChangedMessage: "{prefix} &aNickname updated to &r{nick}"
  NicknameResetMessage: "{prefix} &aNickname reset!"

  # Command error messages
  PlayerOnlyMessage: "{prefix} &cOnly players can execute this command!" # sent when console uses a player only command
  NoPermissionMessage: "{prefix} &cYou don't have permission to do this!" # sent when someone doesn't have the required permissions for a command
  MissingArgumentsMessage: "{prefix} &cMissing arguments! Usage: /{command} {args}"
  RankNotFoundMessage: "{prefix} &cThe &r{rank} &crank does not exist!"
  PlayerNotFoundMessage: "{prefix} &cPlayer &r{player} &cnot found!"