messages:
  # Placeholders:
  # {prefix}: reference to the prefix message set below
  # {rank}: reference to the rank of the player affected (or default rank if no rank has been assigned)


  prefix: "[&bCC&r]" # can be used in messages using the '{prefix}' placeholder

  # Join Leave messages (placeholder: {player} the target player, {rank} the target players rank)
  JoinMessage: "{prefix} {rank} {player} Has joined the game!"
  LeaveMessage: "{prefix} {rank} {player} Has left the game!"

  # Only sent to people with the 'crystalcore.vanish' permission
  SilentJoinMessage: "{prefix} {rank} {player} Has silently joined the game!" # sent when someone auto vanishes
  SilentLeaveMessage: "{prefix} {rank} {player} Has silently left the game!" # sent when someone leaves vanished
  SelfVanishMessage: "{prefix} You have vanished!"
  SelfUnvanishMessage: "{prefix} You have reappeared!"
  OtherVanishMessage: "{prefix} {rank} {player} Has vanished!"
  OtherUnvanishMessage: "{prefix} {rank} {player} Has reappeared!"

  # Rank messages (placeholder: {rank} new rank name)
  RankChangedMessage: "{prefix} &aYour rank has been updated to &r{rank}!"
  RankChangedOtherMessage: "{prefix} &aUpdated &r{player}'s &arank to &r{rank}"
  TempRankChangedMessage: "{prefix} &aYou have temporarily been given the &r{rank} &arank! your rank will revert back once you leave."
  TempRankChangedOtherMessage: "{prefix} &aTemporarily updated &r{player}'s &arank to &r{rank}"
  RankDeletedMessage: "{prefix} &cThe rank you had has been deleted! you have been reverted to the default rank."

  # /nickname messages (placeholder: {nickname} new nickname)
  NicknameChangedMessage: "{prefix} &aNickname updated to &r{nick}"
  NicknameResetMessage: "{prefix} &aNickname reset!"

  # /message messages (placeholders: {sender} sender, {receiver} receiver, {message} message)
  DirectMessageSentMessage: "&6[&r{sender} &6->&r {receiver}&6] &r{message}"
  DirectMessageReceivedMessage: "&6[&r{receiver} &6<-&r {sender}&6] &r{message}"

  # Command error messages
  PlayerOnlyMessage: "{prefix} &cOnly players can execute this command!" # sent when console uses a player only command
  NoPermissionMessage: "{prefix} &cYou don't have permission to do this!" # sent when someone doesn't have the required permissions for a command
  MissingArgumentsMessage: "{prefix} &cMissing arguments! Usage: /{command} {args}"
  RankNotFoundMessage: "{prefix} &cThe &r{rank} &crank does not exist!"
  RankExistsMessage: "{prefix} &cThe &r{rank} &calready exists!" # sent when someone tries to create a rank with the same name as an existing rank
  RankIsDefaultMessage: "{prefix} &cYou cannot delete the default rank!" # sent when someone tries to delete the default rank
  RankAlreadyDefaultMessage: "{prefix} &cThis rank already is the default rank!" # sent when someone tries to set the default rank to the default rank
  PlayerNotFoundMessage: "{prefix} &cPlayer &r{player} &cnot found!"
  NoColorCodesMessage: "{prefix} &cRank names cannot contain color codes!" # sent when someone tries to use color codes in rank name
  PermissionNotFoundMessage: "{prefix} &cThe &r{rank} &crank does not have the &r{permission} &cpermission"
  PermissionAlreadyFoundMessage: "{prefix} &cThe &r{rank} &crank already has the &r{permission} &cpermission"

  # Command responses
  GamemodeChangedMessage: "{prefix} &aYour gamemode has been updated to &r{gamemode}"
  GamemodeChangeOtherMessage: "{prefix} &aUpdated &r{player}'s &agamemode to &r{gamemode}"
  RankCreatedMessage: "{prefix} &aCreated the &r{rank} &arank!"
  RankDeletedCMDMessage: "{prefix} &cDeleted the &r{rank} &crank!"
  RankPrefixChangedMessage: "{prefix} &aUpdated &r{rank}'s &aPrefix to &r{rankPrefix}"
  RankPermissionAddedMessage: "{prefix} &aAdded the &r{permission} &apermission to &r{rank}"
  RankPermissionRemovedMessage: "{prefix} &cRemoved the &r{permission} &cpermission from &r{rank}"
  DefaultRankChangedMessage: "{prefix} &aChanged the default rank to the &r{rank} &arank"